import { jsPDF } from "jspdf";

export const handleDownloadPDF = (result: string) => {
    const doc = new jsPDF();

    const text = result;
    const marginLeft = 10;
    const marginTop = 30; // Increased to make room for header
    const maxWidth = 180;
    const lineHeight = 10;
    const pageHeight = doc.internal.pageSize.height;
    const pageWidth = doc.internal.pageSize.width;

    // Split text into lines
    const lines = doc.splitTextToSize(text, maxWidth);

    let currentHeight = marginTop;
    let currentPage = 1;
    let totalPages = Math.ceil((lines.length * lineHeight) / (pageHeight - marginTop - 20));

    const addHeaderAndFooter = () => {
        // Add header
        doc.setFontSize(10);
        doc.text("Generated by example.com", pageWidth / 2, 10, { align: "center" });

        // Add footer
        doc.setFontSize(10);
        doc.text("© 2023 All rights reserved", pageWidth / 2, pageHeight - 10, { align: "center" });

        // Add page numbers
        doc.text(`Page ${currentPage}/${totalPages}`, pageWidth - 20, pageHeight - 10);
    };

    lines.forEach((line: string) => {
        if (currentHeight + lineHeight > pageHeight - 20) {
            addHeaderAndFooter();
            doc.addPage();
            currentPage++;
            currentHeight = marginTop;
        }

        doc.setFontSize(12); // Reset font size for main content
        doc.text(line, marginLeft, currentHeight);
        currentHeight += lineHeight;
    });

    // Add header and footer to the last page
    addHeaderAndFooter();

    doc.save("transcript.pdf");
};
